version: '3'

services:
  api:
    build: ./web
    ports:
      - "5000:5000"
    links:
      - db
  db:
    build: ./db
    ports:
      - "27017:27017"
  front:
    image: analise-ativos
    build: ../analise-de-investimentos
    ports:
      - "80:80"